theme: minima
title: Skill Development
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Grinding in grad school to develop skills

# social links
instagram_username: payley # DO NOT include the @ character, or else the build will fail!
github_username:  payley # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
